import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';

// A dedicated server keeps every edit in this test out of the user's project.
const server=spawn(process.env.PYTHON||resolve('../.venv/Scripts/python.exe'),[resolve('../visualizer.py'),'--no-browser','--port','0'],{cwd:resolve('..'),windowsHide:true});
const url=await new Promise((resolve,reject)=>{
 const timer=setTimeout(()=>reject(new Error('Server startup timed out')),30000);
 server.stdout.on('data',chunk=>{const match=String(chunk).match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});
 server.on('error',reject);
});
const checks=[];const pass=s=>{checks.push(s);console.log('PASS',s);};
let browser;
try{
 browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1600,height:1060}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const current=async()=>await(await page.request.get(url+'/api/project')).json();
 const edit=async(action,ok=true)=>{
  const response=page.waitForResponse(r=>r.url().endsWith('/api/calculate')&&r.request().method()==='POST');
  await action();const result=await(await response).json();
  if(ok){assert.ok(!result.error,result.error);await page.waitForFunction(()=>document.querySelector('.project-title small')?.textContent.includes('Calculated'));}
  return result;
 };
 const nav=async label=>{await page.getByRole('button',{name:label,exact:true}).click();await page.locator('.planning-surface').evaluate(el=>el.scrollTop=0);};
 const field=label=>page.getByLabel(label,{exact:true});
 const svgPoint=async(x,y)=>await page.getByRole('img',{name:'Mezzanine layout designer',exact:true}).evaluate((svg,{x,y})=>{const p=svg.createSVGPoint();p.x=x;p.y=y;const q=p.matrixTransform(svg.getScreenCTM());return{x:q.x,y:q.y};},{x,y});
 const draw=async(x0,y0,x1,y1)=>{
  await page.getByRole('button',{name:'Draw area',exact:true}).click();
  await page.getByRole('img',{name:'Mezzanine layout designer',exact:true}).scrollIntoViewIfNeeded();
  const a=await svgPoint(x0,y0),b=await svgPoint(x1,y1);
  await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();
 };
 await page.goto(url);await page.getByRole('img',{name:'Editable building plan',exact:true}).waitFor();
 await mkdir('test-results',{recursive:true});
 assert.equal(await page.locator('.design-panel').count(),0);assert.equal(await page.locator('.inspector').count(),0);
 assert.ok((await page.getByRole('img',{name:'Editable building plan'}).boundingBox()).width>1400);
 assert.equal(await page.locator('canvas').count(),0);
 await page.screenshot({path:'test-results/workspace-building.png'});
 pass('Building designer uses full width with contextual inputs and no permanent sidebars');
 let model=await edit(()=>field('Bay width (ft)').fill('48'));assert.equal(model.grid.width_ft,128);
 model=await edit(()=>field('Joist spaces in selected bay').fill('8'));assert.equal(model.project.joists_per_bay[0].joist_spaces,8);
 const grid=await field('Move X grid 2').boundingBox();
 model=await edit(async()=>{await page.mouse.move(grid.x+grid.width/2,grid.y+grid.height*.2);await page.mouse.down();await page.mouse.move(grid.x+grid.width/2+20,grid.y+grid.height*.2,{steps:4});await page.mouse.up();});assert.equal(model.grid.width_ft,128);
 pass('Bay dimensions, joist spaces, and dragged grids recalculate directly from the plan');
 let releaseResponse,markHeld;
 const held=new Promise(resolve=>{markHeld=resolve;}),release=new Promise(resolve=>{releaseResponse=resolve;});
 await page.route('**/api/calculate',async route=>{const response=await route.fetch();markHeld();await release;await route.fulfill({response});},{times:1});
 await field('Bay width (ft)').fill('42');await held;await field('Bay width (ft)').fill('44');releaseResponse();
 await page.waitForFunction(()=>document.querySelector('.project-title small')?.textContent.includes('Calculated')&&document.querySelector('[aria-label="Bay width (ft)"]')?.value==='44');
 assert.equal((await current()).project.x_spans_ft[0],44);
 await edit(()=>page.getByRole('button',{name:'Undo last change',exact:true}).click());assert.equal((await current()).project.x_spans_ft[0],42);
 await edit(()=>page.getByRole('button',{name:'Redo last change',exact:true}).click());assert.equal((await current()).project.x_spans_ft[0],44);
 pass('Rapid edits survive calculations in progress and support undo/redo');
 await page.getByRole('button',{name:'Grid & dimensions',exact:true}).click();await page.getByText('Build a regular grid',{exact:true}).click();
 await field('X bays').fill('3');await field('Y bays').fill('2');await field('X spacing (ft)').fill('40');await field('Y spacing (ft)').fill('40');
 model=await edit(()=>page.getByRole('button',{name:'Replace grid',exact:true}).click());assert.deepEqual(model.project.x_spans_ft,[40,40,40]);
 assert.ok((await page.locator('dialog').boundingBox()).width>1000);await page.getByRole('button',{name:'Done',exact:true}).click();
 pass('Grid dimensions and regular-grid creation have a wide editor');
 await page.getByRole('button',{name:'Collateral',exact:true}).click();model=await edit(()=>page.getByRole('button',{name:'Bay B2',exact:true}).click());assert.ok(model.project.collateral_bays.some(b=>b.x_bay===2&&b.y_bay==='B'));
 await page.getByRole('button',{name:'Speed bays',exact:true}).click();model=await edit(()=>page.getByRole('button',{name:'Bay B2',exact:true}).click());assert.ok(model.project.speed_bay_rows.includes(1));
 await nav('Roof section');model=await edit(()=>field('Clear height').fill('28'));assert.equal(model.roof_profile.clear_height_ft,28);assert.ok((await page.locator('.roof-controls').boundingBox()).width>1400);
 model=await edit(()=>field('Roof profile').selectOption('Gable'));assert.ok(model.roof_profile.bay_slopes_ft_per_ft.some(v=>v!==0));
 pass('Collateral, speed bays, and roof controls retain the original automatic workflow');
 await nav('Loads & foundations');const volume=model.takeoffs.footings.summary.total_cy;
 model=await edit(()=>field('Footing depth').fill('2'));assert.ok(Math.abs(model.takeoffs.footings.summary.total_cy-volume*2)<.001);
 await page.screenshot({path:'test-results/workspace-loads.png'});
 pass('Loads and foundations use a full-width form and update concrete quantities');
 // Add the selected bay (B2), then place it at A1 using absolute dimensions.
 await nav('Mezzanines');model=await edit(()=>page.getByRole('button',{name:'Add first mezzanine',exact:true}).click());
 assert.equal(model.results.mezzanine.summary.zone_count,1);let zoneId=model.project.mezzanines[0].id;
 await edit(()=>field('Mezzanine X position (ft)').fill('0'));await edit(()=>field('Mezzanine Y position (ft)').fill('0'));
 model=await edit(()=>field('Mezzanine length (ft)').fill('30'));
 assert.equal(model.results.mezzanine.summary.total_mezzanine_area_sf,1200);assert.ok(model.takeoffs.mezzanine_footings.summary.column_count>0);
 const mzMembers=()=>model.members.filter(m=>m.level==='mezzanine');
 assert.ok(mzMembers().some(m=>m.type==='joist'&&m.section.assigned));assert.ok(mzMembers().some(m=>m.type==='girder'));assert.ok(mzMembers().some(m=>m.type==='column'));
 pass('Placing a mezzanine calculates joists, girders, additional columns and pad footings');
 const oldDemand=model.results.mezzanine.mezzanine_joist_calculations[0].required_capacity_plf;
 model=await edit(()=>field('Mezzanine live load (psf)').fill('150'));assert.ok(model.results.mezzanine.mezzanine_joist_calculations[0].required_capacity_plf>oldDemand);
 model=await edit(()=>field('Mezzanine dead load (psf)').fill('40'));assert.equal(model.results.mezzanine.mezzanine_zones[0].total_load_psf,190);
 model=await edit(()=>field('Mezzanine joist direction').selectOption('horizontal'));assert.equal(model.results.mezzanine.mezzanine_zones[0].joist_direction,'horizontal');
 model=await edit(()=>field('Mezzanine X bays').fill('2'));model=await edit(()=>field('Mezzanine Y bays').fill('2'));assert.equal(model.results.mezzanine.mezzanine_zones[0].panel_count,4);
 await page.locator('.mezz-properties').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/workspace-mezz-properties.png'});
 pass('Separate floor loads, joist direction, and internal X/Y framing bays control the calculations');
 await page.getByRole('button',{name:'Edit joist panels',exact:true}).click();
 await page.getByRole('button',{name:'Mezzanine panel 1,1',exact:true}).click();
 model=await edit(()=>field('Selected panel joist spaces').fill('9'));assert.equal(model.project.mezzanines[0].joist_spaces_overrides['1,1'],9);
 pass('Individual framing panels have directly editable joist-space overrides');
 await page.getByRole('button',{name:'Select / move',exact:true}).click();
 const handle=page.getByRole('button',{name:'Resize mezzanine se',exact:true});await handle.scrollIntoViewIfNeeded();
 const box=await handle.boundingBox(),target=await svgPoint(40,40);
 model=await edit(async()=>{await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(target.x,target.y,{steps:6});await page.mouse.up();});
 assert.equal(model.project.mezzanines[0].y_end_ft,40);assert.deepEqual(model.project.mezzanines[0].internal_y_spacings_ft,[20,20]);
 pass('Corner resizing snaps to grids and preserves the internal framing subdivision');
 model=await edit(()=>draw(40,40,80,80));assert.equal(model.results.mezzanine.summary.zone_count,2);
 const newest=model.project.mezzanines[1].id;
 await page.getByRole('button',{name:'Select / move',exact:true}).click();
 const from=await svgPoint(60,60),to=await svgPoint(100,60);
 model=await edit(async()=>{await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:8});await page.mouse.up();});
 assert.equal(model.project.mezzanines.find(z=>z.id===newest).x_start_ft,80);
 model=await edit(()=>page.getByRole('button',{name:'Remove area',exact:true}).click());assert.equal(model.results.mezzanine.summary.zone_count,1);
 pass('A second mezzanine can be drawn, moved, selected, and removed');
 await field('Mezzanine snapping').selectOption('half');
 const invalid=await edit(()=>draw(10,10,20,20),false);assert.match(invalid.error,/at least 2 support connections/);
 assert.equal((await current()).results.mezzanine.summary.zone_count,1);
 await page.getByRole('button',{name:'Undo last change',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.project-title small')?.textContent.includes('Calculated'));
 pass('Unsupported mezzanines show a useful engine error and preserve the last valid results');
 await page.getByRole('button',{name:'Calculations',exact:true}).click();await page.getByRole('button',{name:'Show calculation details',exact:true}).click();
 assert.ok(await page.locator('.mezz-member-table tbody tr').count()>0);
 const [csv]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Export mezzanine CSV',exact:true}).click()]);assert.ok((await readFile(await csv.path(),'utf8')).includes(zoneId));
 await page.screenshot({path:'test-results/workspace-mezz-calculations.png'});
 pass('Mezzanine calculations expose member demands, selections, quantities, and CSV export');
 await nav('Takeoffs');await field('Takeoff building level').selectOption('mezzanine');
 assert.equal(await page.locator('.takeoff-report tbody tr').count(),(await current()).members.filter(m=>m.type==='joist'&&m.level==='mezzanine').length);
 await page.getByRole('button',{name:'Footings',exact:true}).click();assert.equal(await page.locator('.takeoff-report tbody tr').count(),(await current()).takeoffs.mezzanine_footings.summary.column_count);
 pass('Takeoff tables can isolate mezzanine steel and additional footings');
 const [saved]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Save project',exact:true}).click()]);
 const savedProject=JSON.parse(await readFile(await saved.path(),'utf8'));model=await edit(()=>page.locator('input[type=file]').setInputFiles({name:'reopen.steel.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(savedProject))}));
 assert.equal(model.project.mezzanines[0].joist_spaces_overrides['1,1'],9);assert.equal(model.results.mezzanine.mezzanine_zones[0].total_load_psf,190);
 pass('Saving and reopening preserves mezzanine geometry, floor loads, and panel overrides');
 await page.getByRole('button',{name:'Joists',exact:true}).click();const memberId=await page.locator('.takeoff-report tbody tr td:first-child').first().innerText();await page.locator('.takeoff-report tbody tr').first().click();
 await page.locator('canvas').waitFor();assert.equal(await page.locator('.member-heading h2').innerText(),memberId);
 await page.getByRole('button',{name:'Choose steel section',exact:false}).click();await page.getByText('Specify a custom section',{exact:true}).click();await field('Designation').fill('MEZZ PIN');await field('Nominal depth').fill('36');await field('Unit weight').fill('12.5');await field('Apply selection to').selectOption('member');await page.getByRole('button',{name:'Apply section',exact:true}).click();await page.locator('dialog').waitFor({state:'detached'});assert.ok((await current()).members.some(m=>m.section.designation==='MEZZ PIN'));
 pass('Mezzanine schedule rows open the 3D member inspector and allow pinned steel choices');
 await nav('Building layout');await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'test-results/workspace-laptop.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await nav('Mezzanines');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/workspace-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 pass('Laptop and phone layouts remain navigable without JavaScript errors');
 console.log(JSON.stringify({passed:checks.length,checks},null,2));
}finally{await browser?.close();server.kill();}
