import React,{useRef,useState} from 'react';
import {MousePointer2,Grid3X3,Ruler,Plus,Minus,Maximize,Layers3,Building2,ArrowDownToLine,Download,Check,Info} from 'lucide-react';

const sum=a=>a.reduce((s,n)=>s+Number(n||0),0);
const lines=a=>a.reduce((out,n)=>[...out,out.at(-1)+Number(n||0)],[0]);
const letter=i=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;};
const number=(v,d=2)=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:d});
const ft=v=>`${number(v)}′`;
const same=(b,x,y)=>Number(b.x_bay)===x+1&&b.y_bay===letter(y);
const toggleBay=(list,x,y)=>list.some(b=>same(b,x,y))?list.filter(b=>!same(b,x,y)):[...list,{x_bay:x+1,y_bay:letter(y)}];
export function QuickGrid({draft,setDraft}){
 const [nx,setNx]=useState(draft.x_spans_ft.length),[ny,setNy]=useState(draft.y_spans_ft.length),[sx,setSx]=useState(draft.x_spans_ft[0]),[sy,setSy]=useState(draft.y_spans_ft[0]);
 return <details className="quick-grid"><summary>Build a regular grid</summary><p>Set bay counts and spacing, then replace the current grid.</p><div className="quick-grid-fields">{[['X bays',nx,setNx,1,24],['X spacing (ft)',sx,setSx,1,200],['Y bays',ny,setNy,1,24],['Y spacing (ft)',sy,setSy,1,200]].map(([label,v,set,min,max])=><label key={label}>{label}<input aria-label={label} type="number" min={min} max={max} value={v} onChange={e=>set(e.target.value)}/></label>)}</div><button className="button full" disabled={!(nx>=1&&nx<=24&&ny>=1&&ny<=24&&Number.isInteger(+nx)&&Number.isInteger(+ny)&&sx>=1&&sx<=200&&sy>=1&&sy<=200)} onClick={()=>setDraft(p=>({...p,x_spans_ft:Array(+nx).fill(+sx),y_spans_ft:Array(+ny).fill(+sy),joists_per_bay:[],roof_line_elevations_ft:undefined}))}>Replace grid</button></details>;
}

export function PlanEditor({draft,setDraft,selectedBay,setSelectedBay,data}){
 const [tool,setTool]=useState('edit'),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});
 const svg=useRef(),drag=useRef();
 const xSpans=draft.x_spans_ft.map(v=>Math.max(.5,Number(v)||.5)),ySpans=draft.y_spans_ft.map(v=>Math.max(.5,Number(v)||.5));
 const xs=lines(xSpans),ys=lines(ySpans),width=xs.at(-1)||1,length=ys.at(-1)||1;
 const pad=Math.max(width,length)*.15,viewW=width+pad*2,viewH=length+pad*2,font=Math.max(width,length)/45;
 const point=e=>{const p=svg.current.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.current.getScreenCTM().inverse());};
 const inactive=(x,y)=>(draft.inactive_bays||[]).some(b=>same(b,x,y));
 const active=(x,y)=>x>=0&&y>=0&&x<xs.length-1&&y<ys.length-1&&!inactive(x,y);
 const boundary=[];
 for(let y=0;y<ys.length;y++)for(let x=0;x<xs.length-1;x++)if(active(x,y-1)!==active(x,y))boundary.push({o:'H',l:y,s:x,a:[xs[x],ys[y]],b:[xs[x+1],ys[y]]});
 for(let x=0;x<xs.length;x++)for(let y=0;y<ys.length-1;y++)if(active(x-1,y)!==active(x,y))boundary.push({o:'V',l:x,s:y,a:[xs[x],ys[y]],b:[xs[x],ys[y+1]]});
 const hasWall=edge=>draft.perimeter_support==='walls'||(draft.load_bearing_wall_segments||[]).some(e=>e.orientation===edge.o&&e.line_index===edge.l+1&&e.segment_index===edge.s+1);
 const toggleWall=edge=>setDraft(p=>{const source=p.perimeter_support==='walls'?boundary.map(e=>({orientation:e.o,line_index:e.l+1,segment_index:e.s+1})):p.load_bearing_wall_segments||[];const match=e=>e.orientation===edge.o&&e.line_index===edge.l+1&&e.segment_index===edge.s+1;return {...p,perimeter_support:'custom',load_bearing_wall_segments:source.some(match)?source.filter(e=>!match(e)):[...source,{orientation:edge.o,line_index:edge.l+1,segment_index:edge.s+1}]};});
 const clickBay=(x,y)=>{setSelectedBay({x,y});if(tool==='shape')setDraft(p=>({...p,inactive_bays:toggleBay(p.inactive_bays||[],x,y)}));if(tool==='collateral')setDraft(p=>({...p,collateral_bays:toggleBay(p.collateral_bays||[],x,y)}));if(tool==='spacing')setDraft(p=>({...p,joists_per_bay:[...(p.joists_per_bay||[]).filter(b=>!same(b,x,y)),{x_bay:x+1,y_bay:letter(y),joist_spaces:Number(p.joist_spaces)}]}));if(tool==='speed')setDraft(p=>({...p,speed_bay_rows:p.speed_bay_rows.includes(y)?p.speed_bay_rows.filter(v=>v!==y):[...p.speed_bay_rows,y]}));};
 const startDrag=(e,axis,index)=>{if(tool!=='edit'||e.button!==0)return;e.stopPropagation();drag.current={axis,index,spans:[...draft[`${axis}_spans_ft`]],positions:axis==='x'?xs:ys};svg.current.setPointerCapture(e.pointerId);};
 const move=e=>{const d=drag.current;if(!d)return;if(d.axis==='pan'){const rect=svg.current.getBoundingClientRect(),scale=Math.min(rect.width/(viewW/zoom),rect.height/(viewH/zoom));setPan({x:d.pan.x-(e.clientX-d.x)/scale,y:d.pan.y-(e.clientY-d.y)/scale});return;}const p=point(e),v=Math.max(d.positions[d.index-1]+.5,Math.min(d.positions[d.index+1]-.5,Math.round(p[d.axis]*4)/4));const spans=[...d.spans];spans[d.index-1]=+(v-d.positions[d.index-1]).toFixed(2);spans[d.index]=+(d.positions[d.index+1]-v).toFixed(2);setDraft(p=>({...p,[`${d.axis}_spans_ft`]:spans,roof_line_elevations_ft:undefined}));};
 const tools=[['edit',MousePointer2,'Select / drag grids'],['shape',Grid3X3,'Footprint'],['spacing',Ruler,'Joist spaces'],['collateral',Layers3,'Collateral'],['walls',Building2,'Bearing walls'],['speed',ArrowDownToLine,'Speed bays']];
 return <div className="plan-editor"><div className="plan-tools" role="toolbar" aria-label="Layout tools">{tools.map(([id,Icon,label])=><button key={id} className={tool===id?'active':''} aria-pressed={tool===id} onClick={()=>setTool(id)}><Icon size={15}/>{label}</button>)}<span/><button aria-label="Zoom plan in" onClick={()=>setZoom(z=>Math.min(5,z*1.2))}><Plus size={16}/></button><button aria-label="Zoom plan out" onClick={()=>setZoom(z=>Math.max(.5,z/1.2))}><Minus size={16}/></button><button aria-label="Fit layout" onClick={()=>{setZoom(1);setPan({x:0,y:0});}}><Maximize size={16}/></button></div>
 <div className="plan-instructions">{tool==='edit'?'Drag an interior grid line to move it. Click a bay to edit its dimensions and joist spacing.':tool==='shape'?'Click bays to include or remove them from the footprint.':tool==='spacing'?`Click bays to apply ${draft.joist_spaces} joist spaces. Edit the selected bay for a different count.`:tool==='collateral'?'Click bays to toggle the collateral load.':tool==='walls'?'Click an exterior segment to switch between bearing wall and steel support.':'Click a row to toggle a speed bay / dock side.'}<span>Right-drag to pan</span></div>
 <svg className={`plan-svg tool-${tool}`} ref={svg} role="img" aria-label="Editable building plan" viewBox={`${width/2-viewW/zoom/2+pan.x} ${length/2-viewH/zoom/2+pan.y} ${viewW/zoom} ${viewH/zoom}`} onContextMenu={e=>e.preventDefault()} onPointerDown={e=>{if(e.button===2){drag.current={axis:'pan',x:e.clientX,y:e.clientY,pan};svg.current.setPointerCapture(e.pointerId);}}} onPointerMove={move} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
 <defs><pattern id="plan-dots" x="0" y="0" width="5" height="5" patternUnits="userSpaceOnUse"><circle cx="0" cy="0" r=".12" fill="#ccd8df"/></pattern><pattern id="void-hatch" width="3" height="3" patternUnits="userSpaceOnUse"><path d="M0 3L3 0" stroke="#d5dce2" strokeWidth=".15"/></pattern></defs><rect x={-viewW*5} y={-viewH*5} width={viewW*10} height={viewH*10} fill="url(#plan-dots)"/>
 {ySpans.flatMap((span,y)=>xSpans.map((spanX,x)=>{const off=inactive(x,y),collateral=(draft.collateral_bays||[]).some(b=>same(b,x,y)),speed=(draft.speed_bay_rows||[]).includes(y),selected=selectedBay?.x===x&&selectedBay?.y===y,spaces=(draft.joists_per_bay||[]).find(b=>same(b,x,y))?.joist_spaces||draft.joist_spaces;return <g key={`${x}:${y}`} className="plan-bay" role="button" tabIndex={0} aria-label={`Bay ${letter(y)}${x+1}${off?' inactive':''}`} onClick={()=>clickBay(x,y)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();clickBay(x,y);}}}><rect x={xs[x]} y={ys[y]} width={spanX} height={span} fill={off?'url(#void-hatch)':selected?'#e4efd1':collateral?'#dceddc':speed?'#faedda':'#f9fbfd'} stroke={selected?'#719744':'#b1c2ce'} strokeWidth={selected?.5:.12}/>{!off&&Array.from({length:Math.max(0,Math.min(39,spaces-1))},(_,i)=><line key={i} x1={xs[x]+spanX*(i+1)/spaces} x2={xs[x]+spanX*(i+1)/spaces} y1={ys[y]+.6} y2={ys[y+1]-.6} stroke="#8daeb6" strokeWidth=".13" pointerEvents="none"/>)}<rect x={xs[x]+spanX*.16} y={ys[y]+span*.36} width={spanX*.68} height={span*.30} rx=".7" fill={off?'#e9eef1e8':selected?'#e4efd1ee':'#f9fbfdeb'} pointerEvents="none"/><text x={(xs[x]+xs[x+1])/2} y={ys[y]+span*.47} textAnchor="middle" fontSize={font*1.35} fill="#334e60" fontWeight="600" pointerEvents="none">{letter(y)}{x+1}</text><text x={(xs[x]+xs[x+1])/2} y={ys[y]+span*.57} textAnchor="middle" fontSize={Math.min(font,spanX/7,span/8)} fill="#6c8594" pointerEvents="none">{off?'Excluded':spanX<font*10?`${spaces} spaces`:`${spaces} spaces · ${number(spanX/spaces)}′ o.c.`}</text></g>;}))}
 {xs.map((x,i)=><g key={`x${i}`}><line x1={x} x2={x} y1={-pad*.4} y2={length+pad*.22} stroke="#5d778a" strokeWidth=".18"/>{i>0&&i<xs.length-1&&<line aria-label={`Move X grid ${i+1}`} x1={x} x2={x} y1={0} y2={length} stroke="transparent" strokeWidth={font*1.5} className="drag-x" onPointerDown={e=>startDrag(e,'x',i)} style={{pointerEvents:tool==='edit'?'stroke':'none'}}/>}<circle cx={x} cy={-pad*.57} r={font*.95} fill="#f8fafb" stroke="#8fa6b7" strokeWidth=".15"/><text x={x} y={-pad*.57+font*.4} textAnchor="middle" fontSize={font*1.3} fill="#38586e">{i+1}</text>{i<xs.length-1&&<text className="plan-dimension" role="button" tabIndex={0} aria-label={`Edit X bay ${i+1}`} x={(xs[i]+xs[i+1])/2} y={-pad*.14} textAnchor="middle" fontSize={font*1.2} fill="#537589" onClick={()=>{setSelectedBay({x:i,y:selectedBay?.y||0});document.querySelector('[aria-label="Bay width (ft)"]')?.focus();}}>{ft(draft.x_spans_ft[i])}</text>}</g>)}
 {ys.map((y,i)=><g key={`y${i}`}><line x1={-pad*.4} x2={width+pad*.22} y1={y} y2={y} stroke="#5d778a" strokeWidth=".18"/>{i>0&&i<ys.length-1&&<line aria-label={`Move Y grid ${letter(i)}`} x1={0} x2={width} y1={y} y2={y} stroke="transparent" strokeWidth={font*1.5} className="drag-y" onPointerDown={e=>startDrag(e,'y',i)} style={{pointerEvents:tool==='edit'?'stroke':'none'}}/>}<circle cx={-pad*.57} cy={y} r={font*.95} fill="#f8fafb" stroke="#8fa6b7" strokeWidth=".15"/><text x={-pad*.57} y={y+font*.4} textAnchor="middle" fontSize={font*1.3} fill="#38586e">{letter(i)}</text>{i<ys.length-1&&<text x={-pad*.15} y={(ys[i]+ys[i+1])/2} textAnchor="middle" fontSize={font*1.2} fill="#537589" transform={`rotate(-90 ${-pad*.15} ${(ys[i]+ys[i+1])/2})`}>{ft(draft.y_spans_ft[i])}</text>}</g>)}
 {boundary.map(e=><g key={`${e.o}${e.l}:${e.s}`}><line x1={e.a[0]} y1={e.a[1]} x2={e.b[0]} y2={e.b[1]} stroke={hasWall(e)?'#a37e51':'#577c8f'} strokeWidth={hasWall(e)?.65:.25} pointerEvents="none"/><line aria-label={`Wall ${e.o} ${e.l+1} ${e.s+1}`} x1={e.a[0]} y1={e.a[1]} x2={e.b[0]} y2={e.b[1]} stroke="transparent" strokeWidth={font*1.7} style={{cursor:'pointer',pointerEvents:tool==='walls'?'stroke':'none'}} onClick={()=>toggleWall(e)}/></g>)}
 {(data?.members||[]).filter(m=>m.type==='column'&&m.level==='roof').map(m=><rect key={m.id} x={m.start[0]-.7} y={m.start[1]-.7} width="1.4" height="1.4" fill="#536e7e" pointerEvents="none"/>)}
 {(draft.mezzanines||[]).filter(z=>draft.mezzanine_enabled&&z.enabled!==false&&z.x_end_ft>z.x_start_ft).map(z=><g key={z.id} pointerEvents="none"><rect x={z.x_start_ft} y={z.y_start_ft} width={z.x_end_ft-z.x_start_ft} height={z.y_end_ft-z.y_start_ft} fill="#a0bdde22" stroke="#6d83bb" strokeWidth=".5" strokeDasharray="1 1"/><text x={z.x_start_ft+2} y={z.y_end_ft-2} fontSize={font} fill="#6375a1">{z.name} · {ft(z.elevation_ft)}</text></g>)}
 <text x={width/2} y={length+pad*.64} textAnchor="middle" fontSize={font*1.3} fill="#628092">{ft(width)} × {ft(length)} · North at top</text>
 </svg></div>;
}

export function RoofSection({data,large=false}){
 const profile=data.roof_profile,ys=data.grid.y_lines_ft,heights=data.grid.roof_heights_ft,clear=profile?.clear_height_ft??data.project.clear_height_ft;
 const low=Math.min(clear-2,...heights.map(v=>v-1)),high=Math.max(...heights)+2,plotW=840,plotH=150;
 const x=v=>80+v/ys.at(-1)*plotW,y=v=>200-(v-low)/(high-low)*plotH;
 return <section className={`roof-section ${large?'large':''}`}><div className="roof-section-heading"><div><strong>Roof section · North → South</strong><span>{data.project.roof_type} · Clear height {ft(clear)} · {data.project.roof_calculation_mode==='original'?'Original ¼″/ft roof rules':'Explicit eave & rise'}</span></div><small>Elevation window {ft(low)}–{ft(high)} · Vertical scale expanded</small></div><svg viewBox="0 0 1000 250" role="img" aria-label="Roof slope and elevation section"><line x1="80" x2="920" y1={y(clear)} y2={y(clear)} stroke="#aa9475" strokeDasharray="6 4"/><text x="78" y={y(clear)-7} textAnchor="start" fill="#987e56" fontSize="16">Clear {ft(clear)}</text>{ys.map((v,i)=><g key={i}><line x1={x(v)} x2={x(v)} y1="213" y2={y(heights[i])} stroke="#ced8df"/><circle cx={x(v)} cy="228" r="10" fill="#fff" stroke="#adbfce"/><text x={x(v)} y="232" textAnchor="middle" fill="#658092" fontSize="16">{letter(i)}</text><text x={x(v)} y={y(heights[i])-14} textAnchor="middle" fill="#335b71" fontSize="18" fontWeight="600">{ft(heights[i])}</text>{i<ys.length-1&&<><text x={(x(v)+x(ys[i+1]))/2} y="235" textAnchor="middle" fill="#8b9aa6" fontSize="16">{ft(ys[i+1]-v)}</text><text x={(x(v)+x(ys[i+1]))/2} y={(y(heights[i])+y(heights[i+1]))/2-14} textAnchor="middle" fill="#4b8d81" fontSize="18">{number(Math.abs(heights[i+1]-heights[i])/(ys[i+1]-v)*12,3)}″/ft {heights[i+1]>heights[i]?'↗':heights[i+1]<heights[i]?'↘':'—'}</text></>}</g>)}<path d={heights.map((h,i)=>`${i?'L':'M'}${x(ys[i])} ${y(h)}`).join(' ')} fill="none" stroke="#487b85" strokeWidth="3"/>{(profile?.speed_transition_line_indices||[]).map(i=><line key={i} x1={x(ys[i])} x2={x(ys[i])} y1="35" y2="205" stroke="#c3a061" strokeDasharray="4 3"/>)}<text x="24" y="65" fontSize="16" fill="#879aab" transform="rotate(-90 24 65)">Elevation (ft)</text></svg></section>;
}

export function BayInspector({draft,setDraft,bay}){
 if(!bay||bay.x>=draft.x_spans_ft.length||bay.y>=draft.y_spans_ft.length)return <div className="bay-inspector"><strong>Edit a bay</strong><p>Click a bay in the plan. Drag interior grid lines to adjust its dimensions.</p></div>;
 const {x,y}=bay,override=(draft.joists_per_bay||[]).find(b=>same(b,x,y));
 const input=(label,value,change,min=0)=><label className="field"><span>{label}</span><input aria-label={label} type="number" value={value??''} min={min} onChange={e=>change(e.target.value===''?'':+e.target.value)}/></label>;
 const span=(axis,i,v)=>setDraft(p=>{const key=`${axis}_spans_ft`,spans=[...p[key]];spans[i]=v;return {...p,[key]:spans,roof_line_elevations_ft:undefined};});
 return <section className="bay-inspector"><div className="section-heading"><h3>Bay {letter(y)}{x+1}</h3><span>LAYOUT</span></div><div className="two-fields">{input('Bay width (ft)',draft.x_spans_ft[x],v=>span('x',x,v),.5)}{input('Bay length (ft)',draft.y_spans_ft[y],v=>span('y',y,v),.5)}</div>{input('Joist spaces in selected bay',override?.joist_spaces||draft.joist_spaces,v=>setDraft(p=>({...p,joists_per_bay:[...(p.joists_per_bay||[]).filter(b=>!same(b,x,y)),{x_bay:x+1,y_bay:letter(y),joist_spaces:v}]})),1)}<p>{number(draft.x_spans_ft[x]/(override?.joist_spaces||draft.joist_spaces))} ft joist spacing · {number(draft.x_spans_ft[x]*draft.y_spans_ft[y])} sf</p><label className="simple-check"><input type="checkbox" checked={(draft.collateral_bays||[]).some(b=>same(b,x,y))} onChange={()=>setDraft(p=>({...p,collateral_bays:toggleBay(p.collateral_bays||[],x,y)}))}/>Collateral load in this bay</label><label className="simple-check"><input type="checkbox" checked={(draft.speed_bay_rows||[]).includes(y)} onChange={()=>setDraft(p=>({...p,speed_bay_rows:p.speed_bay_rows.includes(y)?p.speed_bay_rows.filter(v=>v!==y):[...p.speed_bay_rows,y]}))}/>Speed bay row {letter(y)}</label></section>;
}

export function TakeoffSummary({data,onDetails}){
 const tf=data.takeoffs,f=(tf?.footings?.summary.total_cy_with_waste||0)+(tf?.mezzanine_footings?.summary.total_cy_with_waste||0);
 return <section className="takeoff-summary"><div className="section-heading"><h3>Calculated takeoffs</h3><Check size={16}/></div>{[['joist','Joists'],['girder','Girders'],['column','Columns']].map(([key,label])=>{const members=data.members.filter(m=>m.type===key),weight=sum(members.map(m=>m.weight_lbs||0));return <button className="takeoff-summary-row" key={key} onClick={()=>onDetails(key)}><span>{label}<small>{members.length} members</small></span><strong>{number(weight/2000,2)}<small>tons</small></strong></button>})}<button className="takeoff-summary-row" onClick={()=>onDetails('footings')}><span>Pad footings<small>{(tf?.footings?.summary.column_count||0)+(tf?.mezzanine_footings?.summary.column_count||0)} pads · includes 10% waste</small></span><strong>{number(f,2)}<small>CY</small></strong></button><button className="takeoff-summary-row" onClick={()=>onDetails('walls')}><span>Wall area<small>Original gross envelope</small></span><strong>{number(tf?.walls?.summary.total_area_sf,0)}<small>sf</small></strong></button>{data.takeoffs?.concrete_summary&&<><button className="takeoff-summary-row" onClick={()=>onDetails&&onDetails('concrete')}><span>Tilt panels</span><strong>{number(data.takeoffs.concrete_summary.tilt_wall_cy,0)}<small>CY · {number(data.takeoffs.tilt_wall_concrete?.summary.max_thickness_in,2)}″</small></strong></button><button className="takeoff-summary-row" onClick={()=>onDetails&&onDetails('concrete')}><span>Slab on grade</span><strong>{number(data.takeoffs.concrete_summary.slab_cy,0)}<small>CY · {number(data.takeoffs.slab?.thickness_in,2)}″</small></strong></button><button className="takeoff-summary-row" onClick={()=>onDetails&&onDetails('concrete')}><span>Total concrete</span><strong>{number(data.takeoffs.concrete_summary.total_cy,0)}<small>CY</small></strong></button></>}<p className={data.summary.unassigned_count?'takeoff-attention':'takeoff-complete'}>{data.summary.unassigned_count?`${data.summary.unassigned_count} members need a catalog choice or revised depth limit.`:'All members have section selections.'}</p><small className="takeoff-disclaimer">Catalog selection follows the original program. Engineering verification remains separate.</small></section>;
}

export function TakeoffReport({data,kind,setKind,onSelect,level='all'}){
 const tf=data.takeoffs||{},members=data.members.filter(m=>m.type===kind&&(level==='all'||m.level===level)),footings=[...(level==='mezzanine'?[]:tf.footings?.column_footings||[]),...(level==='roof'?[]:tf.mezzanine_footings?.column_footings||[])];
 let columns,rows;
 if(kind==='footings'){const sf=data.summary?.column_safety_factor||1,fx=Object.fromEntries((tf.column_safety?.columns||[]).map(c=>[c.column_id,c.required_capacity_factored_kips]));columns=['Column','Grid','Load (kips)',`Factored ×${sf} (kips)`,'Pad size (ft)','Depth (ft)','Volume (CY)'];rows=footings.map(f=>[f.column_id,f.grid,number(f.required_capacity_kips),number(fx[f.column_id]??f.required_capacity_kips*sf),`${number(f.footing_size_ft)} × ${number(f.footing_size_ft)}`,number(f.footing_depth_ft),number(f.footing_volume_cy,3)]);}
 else if(kind==='walls'){columns=['Wall','Length (ft)','Gross area (sf)'];rows=(level==='mezzanine'?[]:['north','south','east','west']).map(dir=>[dir[0].toUpperCase()+dir.slice(1),number(tf.walls?.[`${dir}_wall`]?.length_ft),number(tf.walls?.[`${dir}_wall`]?.area_sf)]);}
 else if(kind==='concrete'){const tw=tf.tilt_wall_concrete,sl=tf.slab;columns=['Element','Detail','Thickness (in)','Area (sf)','Volume (CY)'];rows=[...(tw?.panels||[]).map(p=>[`${p.wall} tilt panel`,`H ${number(p.governing_height_ft,2)} ft${p.governed_by_minimum?' · 7.5″ minimum governs':` · H/50 = ${number(p.required_thickness_raw_in,2)}″`}`,number(p.thickness_in,2),number(p.area_sf),number(p.volume_cy,2)]),...(sl?[['Slab on grade','Active footprint · input thickness',number(sl.thickness_in,2),number(sl.area_sf),number(sl.volume_cy,2)]]:[]),...(tf.footings?[['Spread footings',`${tf.footings.summary.column_count} pads`,'—','—',number(tf.footings.summary.total_cy,2)]]:[])];} else{columns=['Member','Section','Takeoff length (ft)','Demand','Weight (lb)','Selection'];rows=members.map(m=>[m.id,m.section.designation,number(m.weight_length_ft,2),m.demand.required_capacity_plf!==undefined?`${number(m.demand.required_capacity_plf)} plf`:m.demand.required_capacity_kips!==undefined?`${number(m.demand.required_capacity_kips)} kips`:`${number(m.demand.required_capacity_lbs)} lb`,m.weight_lbs===null?'—':number(m.weight_lbs),m.section.auto_selected?'Automatic':m.section.assigned?'User selection':'No catalog match']);}
 const exportRows=()=>{const csv=[columns,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.href=url;a.download=`${kind}-takeoff.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="takeoff-report"><div className="takeoff-report-header"><div className="report-tabs">{[['joist','Joists'],['girder','Girders'],['column','Columns'],['footings','Footings'],['walls','Wall area'],['concrete','Concrete']].map(([id,label])=><button key={id} className={kind===id?'active':''} onClick={()=>setKind(id)}>{label}</button>)}</div><button className="button" onClick={exportRows}><Download size={15}/>Export {kind} CSV</button></div><div className="report-caption">{kind==='footings'?`Soil bearing: ${number(data.project.bearing_capacity_psf)} psf · Pad depth: ${ft(data.project.footing_depth_ft)} · Quarter-foot size increments · Total with waste: ${number((level==='mezzanine'?0:tf.footings?.summary.total_cy_with_waste||0)+(level==='roof'?0:tf.mezzanine_footings?.summary.total_cy_with_waste||0))} CY`:kind==='walls'?(level==='mezzanine'?'Wall envelope area belongs to the main building.':tf.walls?.basis):`${members.length} members · ${number(sum(members.map(m=>m.weight_lbs||0))/2000)} tons · Original catalog selection rules`}</div><div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} onClick={()=>{if(members[i])onSelect(members[i].id);}}>{row.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>{data.notices.filter(n=>n.includes('no catalog match')||n.includes('unavailable')||n.includes('left unassigned')).map((n,i)=><p className="report-note" key={i}><Info size={15}/>{n}</p>)}</section>;
}
